<a href="https://colab.research.google.com/github/Hemant9785/deep-learning-/blob/main/ann_udemy_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [118]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df.iloc[0:4,:]

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0

In [119]:
x_data = df.iloc[:,3:-1]
y_data = df['Exited']


In [120]:
# preprocessing of data
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [121]:
x_data['Gender'] = label_encoder.fit_transform(x_data['Gender']);
x_data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [122]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
geography  = ohe.fit_transform(df[['Geography']]).toarray()
labels= np.array(ohe.categories_).flatten()

df_ = pd.DataFrame(geography,columns=labels)
df_
x_data = pd.concat([x_data,df_],axis='columns')


In [123]:
x_data.drop('Geography',axis=1,inplace=True)


In [124]:
x_data = x_data.values
y_data = y_data.values

In [132]:
x_data

array([[619.,   0.,  42., ...,   1.,   0.,   0.],
       [608.,   0.,  41., ...,   0.,   0.,   1.],
       [502.,   0.,  42., ...,   1.,   0.,   0.],
       ...,
       [709.,   0.,  36., ...,   1.,   0.,   0.],
       [772.,   1.,  42., ...,   0.,   1.,   0.],
       [792.,   0.,  28., ...,   1.,   0.,   0.]])

In [133]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.33, random_state=42)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)




array([[ 1.67588802, -1.10022343, -0.94183739,  0.00934296,  0.47861826,
        -0.90471845, -1.54618507, -1.03555714,  1.50493673, -1.00388816,
         1.74875572, -0.57987798],
       [ 0.30320673,  0.9089063 , -0.17987213,  1.04687659, -0.046891  ,
         0.81978044,  0.64675311,  0.96566376, -1.31177144, -1.00388816,
         1.74875572, -0.57987798],
       [-0.10235819,  0.9089063 ,  0.96307575, -0.33650158,  0.71243126,
        -0.90471845,  0.64675311, -1.03555714, -1.32081469, -1.00388816,
         1.74875572, -0.57987798],
       [-0.41433121, -1.10022343, -0.75134608,  1.04687659,  0.66929659,
        -0.90471845,  0.64675311,  0.96566376, -0.81248345,  0.9961269 ,
        -0.57183516, -0.57987798],
       [-0.68470783,  0.9089063 , -0.56085476,  1.39272114, -1.21648805,
        -0.90471845,  0.64675311, -1.03555714, -1.62891984,  0.9961269 ,
        -0.57183516, -0.57987798]])

In [127]:
ann = tf.keras.models.Sequential()

In [128]:
ann.add(tf.keras.layers.Dense(units=12,activation='relu'))

In [129]:
ann.add(tf.keras.layers.Dense(units=64,activation='relu'))

In [130]:
ann.add(tf.keras.layers.Dense(units=128,activation='relu'))

In [131]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [134]:
ann.compile(optimizer='adam',metrics=['accuracy'],loss='binary_crossentropy')

In [137]:
ann.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
210/210 [==============================] - 1s 4ms/step - loss: 0.3488 - accuracy: 0.8531
Epoch 2/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8564
Epoch 3/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3407 - accuracy: 0.8587
Epoch 4/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3396 - accuracy: 0.8606
Epoch 5/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3351 - accuracy: 0.8630
Epoch 6/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3312 - accuracy: 0.8633
Epoch 7/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8636
Epoch 8/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3286 - accuracy: 0.8625
Epoch 9/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3263 - accuracy: 0.8634
Epoch 10/10
210/210 [==============================] - 0s 2ms/step - loss: 0.3254 - accuracy: 0.8646

In [141]:
pred = ann.predict(x_test)


104/104 [==============================] - 0s 4ms/step


array([[0.09165091],
       [0.01131972],
       [0.10049351],
       [0.10073206],
       [0.11494908]], dtype=float32)

In [142]:
pred = np.array(pred).flatten()

In [155]:
def ind(arr):
  ls = []
  for i in range(0,100):
    if arr[i]>0.5:
      ls.append(i)
  return ls

In [156]:
p = ind(pred)
t = ind(y_test)

In [157]:
p

[9, 10, 11, 12, 25, 36, 41, 52, 54, 71, 72, 81, 85, 87]

In [158]:
t

[7,
 10,
 11,
 12,
 22,
 25,
 35,
 36,
 40,
 41,
 44,
 48,
 53,
 54,
 68,
 72,
 82,
 85,
 87,
 91,
 95,
 97]